### PR TITLE
Feature/pxblue 2551 tree structure

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Tree structure example

Can be seen here: https://pxblue-angular-design-patterns.web.app/lists/tree-structure

### CODE REVIEW

**Comment by emclaug2** [comment]
@mvbela there's some stuff that feels off when clicking around in the example.  

1. For items that don't have any children, will clicking on the row select the item?
2. Is selection hierarchical?  If I select a parent, are the children also selected?
3. For items with no children, does clicking the row select it?

**Comment by huayunh** [comment]
Can you make these arrows centered? 
image

And you may want to work on responsiveness... I don't know if they are intended to be centered this way on mobile.

https://user-images.githubusercontent.com/8997218/140258779-e0554fc1-75cf-4202-ac6c-5561e67fbb32.mov

For the desktop view, you would want a 16px padding when the container width is close to the card width. See here: https://github.com/pxblue/react-design-patterns/pull/101#issuecomment-943667444

**Comment by mvbela** [comment]
Hi @emclaug2 ,

1. The items are only selected when the radio button is clicked, so it should not select the item if the user clicks the row.
2. Yes, if you select the parent, the children are also selected. This means that for the user to select an isolated child, (s)he should click the keyboard_arrow icon to open the parent and click on the item.

Will update the Figma file with the these comments!

**Comment by emclaug2** [comment]
@mvbela Thanks for the clarification!  One more follow-up question here; does the design have to use radio-buttons?  I'm in a situation right now where I'm fighting the framework & struggling to unselect a radio button once selected.  Checkboxes would be easier to implement but only if the design works.

**Comment by emclaug2** [comment]
This example has been updated to use the original radio buttons; should be ready for review now. 
Check it out here: https://pxblue-angular-design-patterns.web.app/lists/tree-structure

@huayunh For the off-centered chevrons, this is something that's going to affect all the mat expansion panels.  I'm trying to figure out where the best place for this fix should go.

**Comment by mvbela** [comment]
Hi @emclaug2,
I've noticed some details on the tree structure. 
 
**On desktop version:**

1. There should be rounded corners (4px)

Captura de ecrã 2021-11-09, às 15 47 03


**Both in mobile and desktop:**

2. Sometimes it happened that I could select multiple radio buttons

Captura de ecrã 2021-11-09, às 15 38 03

3. When an item is selected, the other items do not show change of color in hover

4. There should be a divider between all items

Captura de ecrã 2021-11-09, às 17 05 25

5. On selected items, there shouldn't be a shadow, but a divider

Captura de ecrã 2021-11-09, às 17 08 16

**Comment by emclaug2** [comment]
Thanks for the review @mvbela ; should be ready for another look! I was unable to reproduce #2 though; you're still able to select more than 1 item please let me know the steps to reproduce.

**Comment by daileytj** [comment]
The "move file" button is disabled when there is no folder selected on the mobile view, should this functionality be matched in the desktop view?
### mobile
Screen Shot 2021-11-10 at 9 07 24 AM
### desktop
Screen Shot 2021-11-10 at 9 07 10 AM

**Comment by daileytj** [comment]
This is more of a design comment/critique, but why do we have active "add folder" and "move folder" buttons that don't do anything while also not letting the user know that this is a placeholder. If I saw this example and needed the functionality I would expect to be able to just copy/paste the code to get all the move/add folder functionality.

**Comment by mvbela** [comment]
Yes, the "Move File" button should also be disabled when there is no item selected on desktop

**Comment by emclaug2** [comment]
Demo has been updated.

**Review by daileytj — APPROVED** [review]

**Pull request merged**
