### PR TITLE
Feature/collapsible app bar

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
-  Add collapsible appbar example

### CODE REVIEW

**Comment by emclaug2** [comment]
@jeffvg This example is replacing the existing collapsible appbar example so I'm going to try to update the cypress tests.

**Comment by jeffvg** [comment]
Running in to this error checking the position on collapsible appbar.
(only within the route http://localhost:4200/app-bar/...)
- scroll to collapse the app-bar
- navigate to search bar
- navigate back to collapsible appbar

When navigating back we don't do a reload/refresh of the page

image

**Comment by emclaug2** [comment]
@jeffvg This issue should be fixed now.

You should be able to observe that when you go to the Search page, scroll down, then go the Collapsible AppBar page, the animation from Expanded to Collapsed happens immediately.  Does this seem like a bug?  I'd imagine the appbar should just initialize in it's collapsed state instead of immediately transitioning to it.

**Comment by jeffvg** [comment]
> @jeffvg This issue should be fixed now.
> 
> You should be able to observe that when you go to the Search page, scroll down, then go the Collapsible AppBar page, the animation from Expanded to Collapsed happens immediately. Does this seem like a bug? I'd imagine the appbar should just initialize in the collapsed state instead of immediately transitioning to it.

I see what you mean. Technically in a app this would be a bug but I don't think it's a huge deal for what we are doing. It would be nice to have the 2 pages in the same route treated separately (not scrolling with each other) but not sure if that's possible without a lot of code changes

**Review by jeffvg — APPROVED** [review]
looks good

**Comment by emclaug2** [comment]
I talked to Joe and ideally whenever a route change occurs, the scroll distance should be reset so the user is placed at the top of the page.

**Comment by huayunh** [comment]
> whenever a route change occurs, the scroll distance should be reset

Design-wise, this depends on where the user comes from. If a user traces back from a subpage to its root, sometimes you would want to preserve that scroll distance. For this project, it is perfectly fine to go back to the top.

**Comment by joebochill** [comment]
Huayun is right. I think the browser default behavior is usually to scroll to top when you go forward to a new page, and restore the scroll position when using back/forward. I think SPAs kind of screw around with that though.

**Comment by emclaug2** [comment]
For a quick fix I could add a route listener that manually scrolls a user to the top on route changes; it won't preserve previous scroll distance if a user hits the back button though.

**Review by huayunh — APPROVED** [review]
Looks good.

**Comment by emclaug2** [comment]
I'll make a separate PR for the scroll-top functionality since it's going to affect all pages in the showcase.

**Pull request merged**
