### PR TITLE
Feature/multiselect snackbar

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Fix cypress tests in circle ci

### CODE REVIEW

**Comment by emclaug2** [comment]
I'm having some trouble getting the tests to run locally.  Is the command `yarn cytest`?

**Comment by jeffvg** [comment]
> I'm having some trouble getting the tests to run locally. Is the command `yarn cytest`?

If you want to debug the test you can start ng design patterns up then in a new terminal run "yarn cypress open"

**Comment by emclaug2** [comment]
Have you ever seen this before @jeffvg ?

image

**Comment by jeffvg** [comment]
https://docs.cypress.io/guides/getting-started/installing-cypress.html#yarn-add

**Review by jeffvg — APPROVED** [review]

**Pull request merged**
