### PR TITLE
Feature/i18n currency

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Enhance i18n example
- Add currency format example
- Add current date example

#### Screenshots:

English:
image

French:
image

Chinese:
image

### CODE REVIEW

**Comment by emclaug2** [comment]
The currency translation does not convert monetary value, it instead shows how the currency should be displayed.

**Comment by emclaug2** [comment]
If there is a better place to put the date or price please let me know.

**Comment by jeffvg** [comment]
do we know if the euro symbol should be displayed before the currency amount? €3.93
currently we display euro after the currency amount and has a comma rather then decimal..

**Comment by joebochill** [comment]
> do we know if the euro symbol should be displayed before the currency amount? €3.93
> currently we display euro after the currency amount and has a comma rather then decimal..

Most non-english speaking countries place the Euro symbol after the amount and they use commas for decimal separator and period for thousands separator.

**Comment by huayunh** [comment]
I can confirm the Chinese one looks correct to me :)

**Pull request merged**
