### PR TITLE
Fix/spinner width

### PR DESCRIPTION
**Pull request by ektasawant**
Fixes [104](https://github.com/pxblue/angular-design-patterns/issues/104) .
Match Ng design pattern with react design (spinner overlay)
1. Width should be as per design.
2. Header and footer should not scroll only card content is scrollable.
3. In mobile remove padding from body

### CODE REVIEW

**Review by emclaug2 — COMMENTED** [review]
I'm taking a look at this now but initial impressions are that there's a lot of code changes for such a small issue.  What other changes are part of this PR?

**Comment by jeffvg** [comment]
overall the page does look different. Dev is on left, spinner width branch on right

image

**Comment by ektasawant** [comment]
> I'm taking a look at this now but initial impressions are that there's a lot of code changes for such a small issue. What other changes are part of this PR?

While working on react design pattern (spinner overlay) got to know that ng design pattern is not having following specs as per design.
1. Width should be as per design.
2. Header and footer should not scroll only card content is scrollable.
3. In mobile remove padding from body

This PR contains changes for fixing above issues. I have updated the same her  [104](https://github.com/pxblue/angular-design-patterns/issues/104)

**Comment by jeffvg** [comment]
do we need to revisit the Angular spinner example for this?
Also been seeing this more often.
should we switch to use this for react?
image

image

**Review by emclaug2 — COMMENTED** [review]
Could you adjust the margin on the checkbox & 'I Agree' text?   It's a little tight. 
Screen Shot 2021-09-14 at 10 50 11 AM

**Review by emclaug2 — APPROVED** [review]
Looks good to me, just see comment from before.

**Comment by jeffvg** [comment]
> do we need to revisit the Angular spinner example for this?
> Also been seeing this more often.
> should we switch to use this for react?
> image
> 
> image

same here all looks good except for the question if we should try out the "styleFunctionSx"

**Comment by emclaug2** [comment]
One last thing I noticed; can you vertical center the content? 

image

**Comment by ektasawant** [comment]
> styleFunctionSx



> do we need to revisit the Angular spinner example for this?
> Also been seeing this more often.
> should we switch to use this for react?
> image
> 
> image



> same here all looks good except for the question if we should try out the "styleFunctionSx"
I think this issue is in react design pattern repository.

**Review by jeffvg — APPROVED** [review]

**Comment by ektasawant** [comment]
> One last thing I noticed; can you vertical center the content?
> 
> image

Fixed please review

**Comment by ektasawant** [comment]
> Could you adjust the margin on the checkbox & 'I Agree' text? It's a little tight.
> Screen Shot 2021-09-14 at 10 50 11 AM

fixed please review.

**Review by emclaug2 — APPROVED** [review]

**Pull request merged**
