### PR TITLE
update search with new data & describes blocks

### PR DESCRIPTION
**Pull request by jeffvg**
#### Changes proposed in this Pull Request:
- update the search test with new data points (test was broke)
- update form validation test describe blocks
- 

#### To Test:
-

### CODE REVIEW

**Comment by daileytj** [comment]
One of the i18n/right-to-left tests is failing for me locally. Can you double-check this?
Screen Shot 2021-09-28 at 7 44 35 AM

**Comment by jeffvg** [comment]
> One of the i18n/right-to-left tests is failing for me locally. Can you double-check this? Screen Shot 2021-09-28 at 7 44 35 AM

Not sure if your system caused this or maybe having multiple projects running. Everything locally and CI is passing. Can you try starting project and in new terminal >project-root yarn cy:run to see if you get same results

image
image
image

**Comment by huayunh** [comment]
This guy is failing on mine too

image

Here is the failed screenshot generated by cypress:

R2L -- should display item list RTL (failed)

**Comment by jeffvg** [comment]
> This guy is failing on mine too
> 
> image
> 
> Here is the failed screenshot generated by cypress:
> 
> R2L -- should display item list RTL (failed)

very strange. this has been passing for a while...good on my machine...lol 
I'll change the filter in CI to run on feature branch to see whats kicked up

image

**Comment by jeffvg** [comment]
verified cypress test pass in CI
https://app.circleci.com/pipelines/github/pxblue/angular-design-patterns/578/workflows/5c4ca5d8-69a0-4c75-91be-d12c81867769/jobs/675/parallel-runs/0/steps/0-105

**Review by joebochill — APPROVED** [review]

**Comment by joebochill** [comment]
Did we resolve the local test failing issue here?

**Pull request merged**
