### PR TITLE
Use latest beta package and fix searchbar issue

### PR DESCRIPTION
**Pull request by emclaug2**
#### Changes proposed in this Pull Request:
- Fixes overflow issue on search bar example
- Update component library to latest beta package - this fixes the drawer-content height issue.

### CODE REVIEW

**Comment by jeffvg** [comment]
what was the overflow issue originally ?

**Comment by emclaug2** [comment]
This was an issue with the search bar.  The content of the page was overflowing horizontally so a scrollbar would appear on the bottom of the page.  This was fixed in the ionic design patterns but not angular yet.

**Review by jeffvg — APPROVED** [review]
Was not able to repro the overflow issue in dev branch to see what was going on

**Review by joebochill — APPROVED** [review]
Looks good to me on a fresh clone.

**Pull request merged**
