### PR TITLE
Bug/bottomsheet not displaying

### LINKED ISSUE #45: Bottomsheet not displaying
#### Describe the bug

Bottomsheet not displaying (at least not on Stackblitz)

This holds for both Basic bottomsheet and complex bottomsheet

#### What is the expected behavior?

Should display

#### What are the steps to reproduce?
1. Go to https://stackblitz.com/github/pxblue/angular-design-patterns?file=src%2Fapp%2Fpages%2Foverlays%2Fbasic-bottom-sheet%2Fbasic-bottom-sheet.component.ts
2. Click on the three dots icon on the top
3. Observe that no bottomsheet shows up
4. See the console

#### Screenshots or links to minimum reproduction example

Apparently there is an overlay, but with no sheets
image

Here is the console

image

#### Environment

Angular Stackblitz Chrome Mac

### PR DESCRIPTION
**Pull request by daileytj**
Fixes #45.

#### Changes proposed in this Pull Request:
- Update dependencies to fix bottomsheet not displaying bug

### CODE REVIEW

**Comment by daileytj** [comment]
https://stackblitz.com/github/pxblue/angular-design-patterns/tree/bug/bottomsheet-not-displaying

**Comment by emclaug2** [comment]
Looks good!

**Comment by huayunh** [comment]
Bug count 1/15?

**Comment by emclaug2** [comment]
> Bug count 1/15?

I'd say this counts; also just opened a similar issue for the i18n snackbar not showing up.  Easy 2/15.

**Pull request merged**
